# Generated by Django 5.1 on 2024-08-27 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todo_desription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='desription',
            new_name='description',
        ),
    ]
